languages:
  python: ">= 3.8"
  java: ">= 17"

libraries:
  # Python libraries
  attrs: ">= 23.2.0"
  beautifulsoup4: ">= 4.12.3"
  cattrs: ">= 23.2.3"
  certifi: ">= 2024.7.4"
  charset-normalizer: ">= 3.3.2"
  exceptiongroup: ">= 1.2.2"
  frozendict: ">= 2.4.4"
  greenlet: ">= 3.0.3"
  html5lib: ">= 1.1"
  idna: ">= 3.7"
  lxml: ">= 5.2.2"
  multitasking: ">= 0.0.11"
  numpy: ">= 2.0.1"
  pandas: ">= 2.2.2"
  peewee: ">= 3.17.6"
  platformdirs: ">= 4.2.2"
  psycopg2: ">= 2.9.9"
  pyrate-limiter: ">= 2.10.0"
  python-dateutil: ">= 2.9.0.post0"
  python-dotenv: ">= 1.0.1"
  pytz: ">= 2024.1"
  PyYAML: ">= 6.0.1"
  requests: ">= 2.32.3"
  requests-cache: ">= 1.2.1"
  requests-ratelimiter: ">= 0.7.0"
  six: ">= 1.16.0"
  soupsieve: ">= 2.5"
  SQLAlchemy: ">= 2.0.31"
  SQLAlchemy-Utils: ">= 0.41.2"
  typing_extensions: ">= 4.12.2"
  tzdata: ">= 2024.1"
  url-normalize: ">= 1.4.3"
  urllib3: ">= 2.2.2"
  webencodings: ">= 0.5.1"
  yfinance: ">= 0.2.41"
  TA-Lib: ">= 0.4.21"

  # Java libraries
  spring-context: ">= 6.1.10"
  spring-boot-starter-actuator: ">= 3.3.1"
  spring-boot-starter: ">= 3.3.1"
  spring-boot-starter-data-jpa: ">= 3.3.1"
  spring-boot-starter-test: ">= 3.3.1"
  spring-boot-starter-web: ">= 3.3.1"
  spring-boot-starter-log4j2: ">= 3.3.1"
  postgresql: ">= 42.7.3"
  jackson-dataformat-yaml: ">= 2.13.0"
  commons-csv: ">= 1.8"

frameworks:
  spring-boot: ">= 3.3.1"
  spring: ">= 6.1.10"

build_tools:
  maven: ">= 3.8.0"
